Fix Python3 breakage of action catch-all handler.
If an action throws an exception, this catch-all handler is supposed to
print a nice dialog, and print it too. However, at present, PyKDE4 seems
broken in some way because the use of i18n() and many other APIs causes
whining like this:

Traceback (most recent call last):
  File "/home/zaufi/kde-devel/share/apps/kate/plugins/pate/kate/__init__.py", line 293, in __call__
    return self.f()
  File "/home/zaufi/kde-devel/share/apps/kate/pate/expand/expand.py", line 206, in expandAtCursor
    expansions = loadExpansions(mime)
  File "/home/zaufi/kde-devel/share/apps/kate/pate/expand/expand.py", line 147, in loadExpansions
    for directory in kate.applicationDirectories('expand'):
  File "/home/zaufi/kde-devel/share/apps/kate/plugins/pate/kate/__init__.py", line 399, in applicationDirectories
    return kdecore.KGlobal.dirs().findDirs('appdata', path)
TypeError: KStandardDirs.findDirs(): argument 1 has unexpected type 'str'

So, we want to fix that at least. Will follow up on the mailing list.