Fix compile error under MSVC
Z:\kderoot\git\kate\tests\indenttest.cpp(174) : error C2589: '__stdcall'
: illegal token on right side of '::'.

Somewhere in WinDef.h, there is: #define pascal __stdcall.

Fix this by not using too generic test method names. Prepend 'test'

Already fixed by 20389eb442de0bfe835bbe033ef6b10c5de09e54, however, I'm
still applying this patch because it solves it in a more future-proof
way :)

(cherry picked from commit cd96dbefc6017c48d3a79f8145af96817bcd45db)

Conflicts:
	tests/indenttest.cpp
	tests/indenttest.h