diffwidget.cpp - include QDir to fix compile
Fixes compile error:
```
diffwidget.cpp:649:57: error: calling 'absoluteDir' with incomplete return type 'QDir'
```

(cherry picked from commit 32849f0d33d708144be700cfebb635b6b92df193)